import type { AppState, Opportunity, OrganizationProfile, StudentProfile } from "./types";

const now = "2026-07-25T18:00:00.000Z";

export const seedStudent: StudentProfile = {
  id: "student_am_001",
  accountId: "account_student_demo",
  name: "Amina Rahman",
  age: 16,
  grade: "11th grade",
  zip: "20852",
  city: "North Bethesda, MD",
  travelMiles: 18,
  skills: ["Canva", "Graphic design", "Social media", "Basic web design", "Tutoring", "Public speaking"],
  interests: ["Youth education", "Technology", "Community service", "Digital media"],
  careerGoals: ["Design", "Technology", "Community leadership"],
  causes: ["Youth education", "Food security", "Muslim community development"],
  strengths: ["Visual communication", "Reliability", "Empathy", "Fast learning"],
  growthAreas: ["Professional writing", "Project management"],
  opportunityTypes: ["Internship", "Volunteer", "Mentorship", "Community Project"],
  formats: ["Remote", "Hybrid", "In person"],
  preferredPaid: "Either",
  experienceLevel: "Developing",
  availableDays: ["Friday", "Saturday", "Sunday"],
  weeklyHours: 8,
  jummahAvailability: "Needs flexibility",
  prayerBreaks: true,
  prayerSpace: true,
  halalFood: true,
  urgentOptIn: true,
  flexibility: "Can adjust evening hours with two days of notice.",
  transportation: "Family ride or Metro within 18 miles.",
  accommodations: "Prefers a prayer space and flexible breaks; needs guardian confirmation for late evening events.",
  discoverable: true,
  guardianApproval: true,
  bio: "Student designer and community volunteer interested in using technology and visual communication to strengthen youth programs.",
  freeText: "I make flyers for school clubs, help younger students with homework, and enjoy learning web design. I want opportunities where I can contribute now while becoming a stronger project leader.",
  experiences: [
    {
      id: "exp_amina_1",
      title: "Student Club Media Volunteer",
      organization: "Fictional School Club",
      description: "Designed event flyers and scheduled social-media posts for student programs.",
      skills: ["Canva", "Graphic design", "Social media"],
      hours: 22,
      evidence: "Organization confirmation requested",
      verification: "organization-confirmed",
    },
    {
      id: "exp_amina_2",
      title: "Peer Tutor",
      organization: "Community Study Circle",
      description: "Helped younger students organize assignments and understand introductory math concepts.",
      skills: ["Tutoring", "Communication", "Patience"],
      hours: 18,
      verification: "self-entered",
    },
  ],
  verifiedServiceHours: 25,
  lastUpdated: now,
};

export const seedOrganization: OrganizationProfile = {
  id: "org_rahma_001",
  accountId: "account_org_demo",
  name: "Rahma Youth Collaborative",
  website: "https://example.org",
  email: "demo-org@example.org",
  mission: "Help young people learn, serve, and lead through supervised community projects.",
  programs: ["Youth tutoring", "Food distribution", "Digital outreach", "Mentorship"],
  audience: ["Muslim youth", "Local families", "Community volunteers"],
  location: "Rockville, MD",
  contactName: "Program Coordinator",
  phone: "Demo only",
  youthSafety: "Adult supervisor named on every youth-facing opportunity; controlled introductions; guardian approval when appropriate.",
  privacyStandards: "Only minimum candidate information is shown before a controlled introduction.",
  accommodations: "Prayer breaks, prayer space, Friday flexibility, and halal food are disclosed per listing.",
  verified: true,
  lastUpdated: now,
};

const safetyStrong = {
  adultSupervision: true,
  privacyPolicy: true,
  accessibility: true,
  accommodationClarity: true,
  communityTrust: true,
  missionAlignment: true,
};

export const seedOpportunities: Opportunity[] = [
  {
    id: "opp_media_001",
    orgId: seedOrganization.id,
    orgName: seedOrganization.name,
    title: "Youth Digital Media Assistant",
    type: "Internship",
    description: "Create social-media graphics and short campaign assets for a supervised youth tutoring program.",
    skills: ["Canva", "Graphic design", "Social media"],
    interests: ["Youth education", "Digital media", "Technology"],
    careerGoals: ["Design", "Technology"],
    location: "Rockville, MD",
    zip: "20850",
    latitude: 39.084,
    longitude: -77.1528,
    distanceMiles: 6.8,
    format: "Hybrid",
    availableDays: ["Friday", "Saturday"],
    commitment: "4–6 hours per week for six weeks",
    weeklyHours: 5,
    ageMin: 15,
    ageMax: 18,
    experienceLevel: "Developing",
    deadline: "2026-08-18",
    createdAt: "2026-07-25T15:00:00.000Z",
    paid: true,
    compensation: "$16/hour stipend",
    urgent: false,
    prayerBreaks: true,
    prayerSpace: true,
    halalFood: true,
    jummahCompatible: true,
    supervision: "Adult communications director and youth-program manager present during in-person work.",
    applicationSteps: "Express interest, review the controlled introduction, then submit two sample designs.",
    impact: "Helps local families discover free tutoring support.",
    verified: true,
    status: "open",
    confidence: 0.96,
    missingFields: [],
    safetySignals: safetyStrong,
  },
  {
    id: "opp_clinic_urgent",
    orgId: "org_clinic_demo",
    orgName: "Community Wellness Clinic",
    title: "Urgent Clinic Welcome-Desk Volunteer",
    type: "Volunteer",
    description: "Support a supervised Saturday clinic by greeting families, organizing forms, and guiding visitors to staff.",
    skills: ["Communication", "Reliability"],
    interests: ["Community service", "Food security"],
    careerGoals: ["Community leadership"],
    location: "Silver Spring, MD",
    zip: "20910",
    latitude: 38.9907,
    longitude: -77.0261,
    distanceMiles: 10.4,
    format: "In person",
    availableDays: ["Saturday"],
    commitment: "One Saturday shift, 9:00 AM–1:00 PM",
    weeklyHours: 4,
    ageMin: 16,
    ageMax: 20,
    experienceLevel: "Beginner",
    deadline: "2026-07-28",
    createdAt: "2026-07-25T16:30:00.000Z",
    paid: false,
    compensation: "Verified service hours",
    urgent: true,
    prayerBreaks: true,
    prayerSpace: true,
    halalFood: true,
    jummahCompatible: true,
    supervision: "Clinic volunteer coordinator present for the entire shift.",
    applicationSteps: "Express interest and receive a guardian-aware introduction packet.",
    impact: "Makes a free community clinic easier to navigate for families.",
    verified: true,
    status: "open",
    confidence: 0.91,
    missingFields: [],
    safetySignals: safetyStrong,
  },
  {
    id: "opp_web_mentor",
    orgId: "org_tech_demo",
    orgName: "Crescent Code Collective",
    title: "Beginner Web Design Mentorship",
    type: "Mentorship",
    description: "Join a small virtual cohort led by Muslim software and product-design professionals.",
    skills: ["Basic web design"],
    interests: ["Technology", "Digital media"],
    careerGoals: ["Technology", "Design"],
    location: "Remote",
    zip: "00000",
    latitude: 39.05,
    longitude: -77.1,
    distanceMiles: 0,
    format: "Remote",
    availableDays: ["Sunday"],
    commitment: "Six Sunday sessions, 90 minutes each",
    weeklyHours: 2,
    ageMin: 14,
    ageMax: 19,
    experienceLevel: "Beginner",
    deadline: "2026-08-08",
    createdAt: "2026-07-24T10:00:00.000Z",
    paid: false,
    compensation: "Free mentorship and project feedback",
    urgent: false,
    prayerBreaks: true,
    prayerSpace: false,
    halalFood: false,
    jummahCompatible: true,
    supervision: "Two screened adult facilitators in every group session; no private one-to-one chat.",
    applicationSteps: "Submit a short interest statement and one learning goal.",
    impact: "Builds a pathway into design and software careers.",
    verified: true,
    status: "open",
    confidence: 0.94,
    missingFields: [],
    safetySignals: safetyStrong,
  },
  {
    id: "opp_food_media",
    orgId: seedOrganization.id,
    orgName: seedOrganization.name,
    title: "Community Food Drive Creative Team",
    type: "Community Project",
    description: "Design a flyer, photograph a supervised food drive, and help publish a recap.",
    skills: ["Canva", "Photography", "Social media"],
    interests: ["Community service", "Digital media", "Food security"],
    careerGoals: ["Design", "Community leadership"],
    location: "Gaithersburg, MD",
    zip: "20877",
    latitude: 39.1434,
    longitude: -77.2014,
    distanceMiles: 12.1,
    format: "In person",
    availableDays: ["Saturday", "Sunday"],
    commitment: "Two planning calls and one four-hour event",
    weeklyHours: 4,
    ageMin: 14,
    ageMax: 18,
    experienceLevel: "Beginner",
    deadline: "2026-08-02",
    createdAt: "2026-07-23T12:00:00.000Z",
    paid: false,
    compensation: "Verified service hours and portfolio evidence",
    urgent: false,
    prayerBreaks: true,
    prayerSpace: true,
    halalFood: true,
    jummahCompatible: true,
    supervision: "Adult volunteer coordinator and event team present.",
    applicationSteps: "Express interest and select a creative role.",
    impact: "Supports local families experiencing food insecurity.",
    verified: true,
    status: "open",
    confidence: 0.93,
    missingFields: [],
    safetySignals: safetyStrong,
  },
  {
    id: "opp_data_entry",
    orgId: "org_archive_demo",
    orgName: "Community Heritage Archive",
    title: "Digital Archive Assistant",
    type: "Volunteer",
    description: "Organize public historical records and write short summaries for a community archive.",
    skills: ["Writing", "Data entry"],
    interests: ["Community service"],
    careerGoals: ["Research"],
    location: "Bethesda, MD",
    zip: "20814",
    latitude: 38.9847,
    longitude: -77.0947,
    distanceMiles: 4.2,
    format: "Hybrid",
    availableDays: ["Wednesday", "Thursday"],
    commitment: "3 hours per week",
    weeklyHours: 3,
    ageMin: 16,
    ageMax: 22,
    experienceLevel: "Beginner",
    deadline: "2026-08-20",
    createdAt: "2026-07-22T09:00:00.000Z",
    paid: false,
    compensation: "Service hours",
    urgent: false,
    prayerBreaks: true,
    prayerSpace: false,
    halalFood: false,
    jummahCompatible: true,
    supervision: "Archive coordinator available during every shift.",
    applicationSteps: "Submit a writing sample.",
    impact: "Preserves local community history.",
    verified: false,
    status: "open",
    confidence: 0.72,
    missingFields: ["accessibility details", "prayer-space availability"],
    safetySignals: {
      adultSupervision: true,
      privacyPolicy: true,
      accessibility: false,
      accommodationClarity: false,
      communityTrust: true,
      missionAlignment: true,
    },
  },
  {
    id: "opp_senior_engineering",
    orgId: "org_lab_demo",
    orgName: "Advanced Systems Lab",
    title: "Advanced Engineering Research Intern",
    type: "Internship",
    description: "Support a graduate research team with advanced numerical simulation and technical reporting.",
    skills: ["Python", "Calculus", "Numerical simulation", "Technical writing"],
    interests: ["Engineering", "Research"],
    careerGoals: ["Engineering research"],
    location: "College Park, MD",
    zip: "20742",
    latitude: 38.9897,
    longitude: -76.9378,
    distanceMiles: 23,
    format: "In person",
    availableDays: ["Monday", "Tuesday", "Wednesday", "Thursday"],
    commitment: "20 hours per week",
    weeklyHours: 20,
    ageMin: 18,
    ageMax: 24,
    experienceLevel: "Experienced",
    deadline: "2026-08-01",
    createdAt: "2026-07-21T08:00:00.000Z",
    paid: true,
    compensation: "$22/hour",
    urgent: false,
    prayerBreaks: true,
    prayerSpace: false,
    halalFood: false,
    jummahCompatible: false,
    supervision: "Research supervisor on site.",
    applicationSteps: "Submit transcript and technical work sample.",
    impact: "Supports advanced engineering research.",
    verified: true,
    status: "open",
    confidence: 0.95,
    missingFields: ["accommodation details"],
    safetySignals: {
      adultSupervision: true,
      privacyPolicy: true,
      accessibility: true,
      accommodationClarity: false,
      communityTrust: false,
      missionAlignment: false,
    },
  },
];

export function seedState(): AppState {
  return {
    version: 3,
    accounts: [
      {
        id: "account_student_demo",
        role: "student",
        username: "amina_test",
        password: "demo123",
        displayName: seedStudent.name,
        profileId: seedStudent.id,
        createdAt: now,
      },
      {
        id: "account_org_demo",
        role: "organization",
        username: "org_test",
        password: "demo123",
        displayName: seedOrganization.name,
        profileId: seedOrganization.id,
        createdAt: now,
      },
    ],
    students: [seedStudent],
    organizations: [seedOrganization],
    opportunities: seedOpportunities,
    interests: [],
    conversations: [],
    outreachLeads: [],
    savedOpportunityIds: { [seedStudent.id]: [] },
    dismissedOpportunityIds: { [seedStudent.id]: [] },
    appliedOpportunityIds: { [seedStudent.id]: [] },
    lastMatchRefresh: now,
  };
}
